# Site settings
title:  chenri
SEOTitle: 程日的博客 | BY Blog
email: 1115231865@qq.com
description: "Every failure is leading towards success."
keyword:
url: "http://ChenRiaixx.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ChenRiaixx/ChenRiaixx.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"


# SNS settings
RSS: false
# weibo_username:    残冬旧日
zhihu_username:  
github_username:    ChenRiaixx
facebook_username: 
jianshu_username:   
#twitter_username:  







# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_domain: auto            # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



    }
]
